# Copyright 2020 Foursquare Labs Inc. All Rights Reserved.

scala_library(
  name = 'stats',
  sources = globs('*.scala'),
  dependencies = [
    '3rdparty:finagle',
    'src/jvm/io/fsq/twitter/ostrich/stats',
  ],
)
